### ISSUE TITLE
[PAP3] Some bugs with plugin 0.0.14

### ISSUE THREAD

**Issue by CyberGuerro** [rswilem/winwing-xplane-plugin#19]
After some tests I found these bugs:

- It seems that VERTICAL SPEED DISPLAY LABEL never shown, while other display's label are shown (IAS, HEADING)
- Displays and backlights are ever on 100%, instead they should be on only when BATTERY is ON and they should be dimmerable according with the rest of the main panels
- menù PAPS -> DISPLAY LABELS has no effect at runtime, but I have to restart X-Plane they take effects
- [critical] When PAP3 is connected together with PFP3N, PFP3N display and buttons are not responsive (2/3 seconds to get button action and device display synchronize with aircraft FMC display).
- [critical] When I reload all devices (PAP3 + PFP3N) X-PLANE crash, attached [Log.txt](https://github.com/user-attachments/files/22003336/Log.txt)

I create an unique issue to list all, but Ramon fill free to split them in more specific issues.

**Comment by rswilem** [comment]
@Belnadifia thanks for helping out! For the reload devices, it usually has to do with releasing / freeing a device, but the callbacks still being attached. I'll check why that is happening.

**Comment by Belnadifia** [comment]
@CyberGuerro I'm almost done refactoring the code for the PAP3.
May you try a release that I can provide to you for testing ?

**Comment by Belnadifia** [comment]
Oww 😩
I need to compile again on linux then 😅

**Comment by Belnadifia** [comment]
Done ! 
I compiled it on linux and upload it again on :
https://github.com/Belnadifia/winwing-xplane-plugin/releases/tag/BETA

can you try to download it again ?

**Comment by CyberGuerro** [comment]
Made tests and these are results about points:

1. fixed
2. partially fixed - display and backlight switch on/off depending by battery, but not dimmable (it should depend on Captain Main Panel Brightness)
3. fixed
4. not fixed, just a little bit better (1-2 seconds instead 2-3), but insufficient to be considered usable.
5. fixed

I think this is a positive balance ( 3 points fixed, 2 waiting to be fixed ;-)  )

**Comment by rswilem** [comment]
Very nice work!
@Belnadifia Are you writing to the PAP in every loop? In the FMC code I check for a changed dataref first before starting the write. So I check if any dataref has changed via the last update cycle check, which is a number, and then only draw if the last draw cycle is lower than the current cycle. 

See:
https://github.com/rswilem/winwing-xplane-plugin/blob/d83d9a40a46c7b861d4639cb0cf7cbd850b2f5a6/src/include/products/fmc/product-fmc.cpp#L252-L260

I think the threaded part is really cool, but beware that it can become really hairy really quick, since X-Plane only accepts the changes to datarefs on the main thread. So you will need some queueing system, as I do in the USB code through ‘AppState::executeAfter(0’

**Comment by CyberGuerro** [comment]
Test done:
- Display and backlight: nothing has changed (ever 100%); do you use **laminar/B738/electric/panel_brightness** as dataref dimmer?
- reactivity: I iterated test more then 10 times to get a more precise values:
   - about buttons -> action is ~1 seconds
   - about action -> display's change is ~6 seconds

**Comment by Belnadifia** [comment]
@rswilem 
No, I only send the HID sequence when there’s something to update.
I even added a debug_force after every write() and checked in-game.
Confirmed: no spam in the console — it only sends the HID sequence that needs it (e.g., if a LED changes, only the LED sequence is sent, not LCD or solenoid).
Also, I never write directly to datarefs, I only trigger _toggle or _up/_down commands.
In the last beta I uploaded yesterday on my GitHub release, the thread for PAP3 sending is in place and seems to work fine.
But unfortunately, @CyberGuerro  doesn’t see any improvement on his side.

@CyberGuerro 
Thanks again!
Yes, as I said, backlight sync isn’t implemented yet — for now I only check the has_power dataref for dimming.
I’ll let you know once it’s in. (It’s not hard to add, but right now my priority is to get rid of the lag on the PFP3N when PAP3 is connected.)

**Comment by rswilem** [comment]
@Belnadifia
Right. That is good and exactly how it’s done! I’ll browse through the code and see if I can find anything. Might be a Linux only issue, USB traffic is handled different on every platform. The weird thing is that just the PFP alone seems to work fine. 

@CyberGuerro
If you disconnect the PFP and just try the PAP alone, does it respond any faster?

**Comment by CyberGuerro** [comment]
@Belnadifia I made this little test:

1. start flight with Zibo (cold and dark) and all devices connected.
2. enabled debug log
3. switch on battery and ground power
4. push fmc button and menu button (x 3 times)
5. exit from x-plane

In the log.txt I found many rows like this:
`[Winwing] Write successful via raw write()`

Is it possible that in linux version of plugin something is wrong?

attached [Log.txt](https://github.com/user-attachments/files/22059213/Log.txt)

I hope this help you

**Comment by Belnadifia** [comment]
Ok thank you.
I updated again the BETA release on my fork :
https://github.com/Belnadifia/winwing-xplane-plugin/releases/tag/BETA

I disabled the input part. SO you shouldn't be able to use the physical buttons/Switches/Knobs
But LCD Backlight and LEDs should works if you manipulate it on the virtual MCP.

Can try it alongside with the PFP3N and tell me if in this configuration you still encounter a lag issue on it or no.
Of course, it's just a test, to isolate the problem. If the lag is gone, I have to look more the Input protocol.

**Comment by CyberGuerro** [comment]
Tested:
- about responsivity nothing has changed and many many rows `[Winwing] Write successful via raw write()`
- about backlight dimming works fine, only one thing: when I exit from X-Plane display switch off, but backlight still unchanged instead switch off.

Attached [Log.txt](https://github.com/user-attachments/files/22067100/Log.txt)

**Comment by Belnadifia** [comment]
You confirm that input from PAP3 is not working (disabled) ?

**Comment by Belnadifia** [comment]
Ok ...
I added somme more info in logs so we can try ton know wath device is concerned about these `Write successful via raw write()`. I updated my fork BETA release again

**Comment by Belnadifia** [comment]
😭 Why ?
I'm wondering If I uploaded it correctly ... 
Just re-uplaod it again. 

It should be :
[Unknow] Write successful via raw write()
or
[Device Name] Write successful via raw write()

**Comment by Belnadifia** [comment]
Ok, so it's most of "FMC" Writing.
Is the FMC updated his Display/Backlight when you tested it ? 
I can add more info maybe to track the exact request.

**Comment by CyberGuerro** [comment]
Yes, I test for 3 times to push fmc buttons to test reactivity of it.

BUT....

What if the problem isn't with the PAP3 driver, but with the PFP3N driver, which doesn't handle coexistence with other devices properly?
After all, the PFP3N has never been tested with other devices before.

**Comment by Belnadifia** [comment]
Ok. I added more details (What Method ? What line ?)
Updated Beta blablabla...

I'm so sorry to ask you so many times for testing my BETA. And I thank you so much for testing it all the times ^^

**Comment by CyberGuerro** [comment]
Tested, attached 

[Log.txt](https://github.com/user-attachments/files/22067596/Log.txt)

**PS.**
Don't worry, I'm happy to help developers 👍🏻

**Comment by Belnadifia** [comment]
You still have lag with the pfp3n?

**Comment by CyberGuerro** [comment]
I'm sorry for you, but lag persists:
button -> action ~2-3 secs -> display changes ~6-7 secs.
Attached [Log.txt](https://github.com/user-attachments/files/22068284/Log.txt)

I hope for the future and developers power for issue fixing. Meanwhile I'll continue to be your friendly tester :-)

**Comment by CyberGuerro** [comment]
button **->** action (~2-3 secs) **->** display changes (~4-5) secs.
  |__________________  ~6-8 secs ________________|

I hope to more clear with this :-)

**Comment by CyberGuerro** [comment]
Great!!
When I come back home from work I'll test (this evening. Here is 9.00 am in the morning)

**Comment by Belnadifia** [comment]
Yaaaaay !!  

![Image](https://github.com/user-attachments/assets/c7c19935-cf8a-4fcb-b3e2-996ac985acee)

**Comment by rswilem** [comment]
Thanks a lot for the effort you both. I'll make sure to check out the pull request in the next days. Kind of wound up right now. In any case, thus all sounds very promising! 👌🏼
